name: Publish to pages

on:
  push

jobs:
  publish-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: |
            sudo apt update
            sudo apt install hugo -f
      - name: Generate website
        run: |
            hugo
      - name: Publish
        run: |
            ls -l
