name: Publish to pages

on:
  push

jobs:
  publish-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo
        run: |
            sudo apt-get update
            sudo apt-get install hugo -f
      - name: Generate website
        run: |
            hugo
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: |
            git config --global user.email "rts.pub@pulegium.eu"
            git config --global user.name "Rytis Sileika"
            git clone https://x-access-token:${GITHUB_TOKEN}@github.com/rytis/rytis.github.io.git
            cd rytis.github.io
            git checkout main
            rm -rf *
            cp -rf ${GITHUB_WORKSPACE}/public/*
            git add .
            git commit -m "From commit ${GITHUB_SHA}"
            git push origin master

